lfs-demo:
  image: runmymind/liveforspeed
  volumes:
    - ~/lfs/setup-demo.cfg:/home/lfs/data/setup.cfg
  restart: always
lfs-s1:
  image: runmymind/liveforspeed
  volumes:
    - ~/lfs/setup-s1.cfg:/home/lfs/data/setup.cfg
  restart: always  
lfs-s2:
  image: runmymind/liveforspeed
  volumes:
    - ~/lfs/setup-s2.cfg:/home/lfs/data/setup.cfg
  restart: always
lfs-s3:
  image: runmymind/liveforspeed
  volumes:
    - ~/lfs/setup-s3.cfg:/home/lfs/data/setup.cfg
  restart: always
